---
title: "Site Metrics"
author: "Chelsea Ursaner"
date: "2/15/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Precipitation this season

```{r warning=FALSE, message=FALSE}
# props to Aida from UCLA stats for writing this web scraping script!
# Load necessary packages -------------------------------------------------

library(httr)
library(rvest)
library(dplyr)

# Read html pages, scrape raw data -----------------------------------------
# LA DUCOMMUN RAIN GAUGE - recorded twice daily

ducommun_scrape <- read_html("http://dpw.lacounty.gov/wrd/precip/alert_rain/season_raindata.cfm?id=377")

ducommun_table <- ducommun_scrape %>% html_nodes("td, th") %>% html_text() %>% as.data.frame()
ducommun_table <- ducommun_table[2:nrow(ducommun_table), 1] %>% as.data.frame()

# Format raw data into table ----------------------------------------------
ducommun <- split(ducommun_table, 1:4) %>% as.data.frame()
names(ducommun) <- c("Date_Time", "Raw_Count", "Amount_inches", "Accumulated_inches")
rownames(ducommun) <- 1:nrow(ducommun)
ducommun <- ducommun[2:nrow(ducommun), ]

# USC RAIN GAUGE - recorded hourly

USC_scrape <- read_html("http://dpw.lacounty.gov/wrd/precip/alert_rain/season_raindata.cfm?id=375")

USC_table <- USC_scrape %>% html_nodes("td, th") %>% html_text() %>% as.data.frame()
USC_table <- USC_table[2:nrow(USC_table), 1] %>% as.data.frame()

# Format raw data into table ----------------------------------------------
USC <- split(USC_table, 1:4) %>% as.data.frame()
names(USC) <- c("Date_Time", "Raw_Count", "Amount_inches", "Accumulated_inches")
rownames(USC) <- 1:nrow(USC)
USC <- USC[2:nrow(USC), ]

# SCHOOLHOUSE RAIN GAUGE - recorded twice daily

schoolhouse_scrape <- read_html("http://dpw.lacounty.gov/wrd/precip/alert_rain/season_raindata.cfm?id=450")

schoolhouse_table <- schoolhouse_scrape %>% html_nodes("td, th") %>% html_text() %>% as.data.frame()
schoolhouse_table <- schoolhouse_table[2:nrow(schoolhouse_table), 1] %>% as.data.frame()

# Format raw data into table ----------------------------------------------
schoolhouse <- split(schoolhouse_table, 1:4) %>% as.data.frame()
names(schoolhouse) <- c("Date_Time", "Raw_Count", "Amount_inches", "Accumulated_inches")
rownames(schoolhouse) <- 1:nrow(schoolhouse)
schoolhouse <- schoolhouse[2:nrow(schoolhouse), ]

# HOLLYWOOD RESEVOIR RAIN GAUGE - recorded hourly

hollywood_scrape <- read_html("http://dpw.lacounty.gov/wrd/precip/alert_rain/season_raindata.cfm?id=312")

hollywood_table <- hollywood_scrape %>% html_nodes("td, th") %>% html_text() %>% as.data.frame()
hollywood_table <- hollywood_table[2:nrow(hollywood_table), 1] %>% as.data.frame()

# Format raw data into table ----------------------------------------------
hollywood <- split(hollywood_table, 1:4) %>% as.data.frame()
names(hollywood) <- c("Date_Time", "Raw_Count", "Amount_inches", "Accumulated_inches")
rownames(hollywood) <- 1:nrow(hollywood)
hollywood <- hollywood[2:nrow(hollywood), ]

# Create new precipitation datasets - averages of certain rain guages per region to be more accurate
# For LA metro, use 2-gauge average (USC, LA Ducommun).
# used for rain barrels, green infrastructure (GI), and incidental capture
# LA_precip <- mean(USC[1,4], ducommun[1,4])     ---    not working because of whitespace in the dataset 
# to continue testing the script, temporarily set to ducommun
LA_precip = ducommun 

# for San Fernando Valley, use average of Schoolhouse DB (gauge 450) and Hollywood resevoir (gauge 312)
# to continue testing the script, temporarily set to ducommun
SFV_precip = ducommun 
```

## Spreading Grounds

Total capture this season

```{r}
# load the RSocrata package
library(RSocrata)
#Read spreading ground capture dataset
spreading <- read.socrata("https://data.lacity.org/A-Livable-and-Sustainable-City/Spreading-Grounds-Centralized-Monthly-Capture/cy8h-q3bu")
#prep data
spreading <- na.omit(spreading)

#load dplyr if not already
library(dplyr)
#calculate spreading ground capture this season
this_season <- spreading %>% select(-Month) %>% group_by(Rain.Season) %>% summarize_all(sum) %>%
  filter(Rain.Season == "2017-2018") %>% select(-Rain.Season)
#sum all spreading grounds to get cumulative 
rowSums(this_season)
```

Spreading capture this season = `r rowSums(this_season)` acre feet.

## Rain Barrels and Cisterns

```{r}
# Read capture capacity dataset
# load the RSocrata package if not already
library(RSocrata)
# Read rain barrels & cisterns capacity dataset
barrels <- read.socrata("https://data.lacity.org/A-Livable-and-Sustainable-City/Rain-Barrels-And-Cisterns-Issued-Through-LAWDP-Reb/a5vt-xsyi")
#prep data
barrels <- na.omit(barrels)

# Read precipitation dataset for LA metro
glimpse(LA_precip)

# Perform calculations to get total capture this season
# Precipitation in LA metro * volumes for small, medium, large rain barrels and cisterns

# Total small cistern capacity, today's small cistern capacity

```

## Incidental Capture

```{r}
# No capacity dataset - use a static numbers of average incidental capture per season
# Average year capture for San Fernando Valley is 29,900 Acre Ft according to the Stormwater Capture Master Plan
incidental_avg_SFV <- 29900
# Average year capture for LA Metro area is 5,100 Acre Ft 
incidental_avg_LA <- 5100

# Read precipitation datasets
# For SFV, use average of Schoolhouse DB (gauge 450) and Hollywood resevoir (gauge 312)

# For LA Metro, use average of LA Ducommun and USC

# Perform calculations to get total capture this season
```

## Green Infrastructure

```{r}
# Read GI projects dataset
GI <- read.socrata("https://data.lacity.org/A-Livable-and-Sustainable-City/Rain-Barrels-And-Cisterns-Issued-Through-LAWDP-Reb/a5vt-xsyi")

# Read precipitation datasets
# Use 2-gauge average (USC, LA Ducommun)

# Perform calculations to get total capture this season

```

## Total Capture - All Methods
```{r}
# Create a table that records a time stamp and the total capture per method
# Write table to Socrata using RSocrata package

```

